[build]
  publish = "."
  command = "echo 'Building static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Inyectar variables de entorno en el HTML
[[plugins]]
  package = "@netlify/plugin-env-inject"

  [plugins.inputs]
    # Variables que se inyectarán en window.NETLIFY_ENV
    SUPABASE_URL = ""
    SUPABASE_ANON_KEY = ""