[build]
  publish = "."
  command = "echo 'Building static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Las variables de entorno ahora se configuran en config.js
# No necesitamos el plugin de inyección de variables